# Film Genre Statistics
# Movie genre statistics and revenue data from 1995-2018
# By Throwback Thursday

# This dataset contains genre statistics for movies released between 1995 and 2018. It provides information on various aspects of the movies, such as gross revenue, tickets sold, 
# and inflation-adjusted figures. The dataset includes columns for genre, year of release, number of movies released in each genre and year, total gross revenue generated by movies 
# in each genre and year, total number of tickets sold for movies in each genre and year, inflation-adjusted gross revenue that takes into account changes in the value of money over 
# time, title of the highest-grossing movie in each genre and year, gross revenue generated by the highest-grossing movie in each genre and year, and inflation-adjusted gross revenue 
# of the highest-grossing movie in each genre and year. This dataset offers insights into film industry trends over a span of more than two decades.

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Understanding the Columns
# Before diving into the analysis, let's familiarize ourselves with the different columns in this dataset:

# Genre: This column represents the genre of each movie.
# Year: The year in which the movies were released.
# Movies Released: The number of movies released in a particular genre and year.
# Gross: The total gross revenue generated by movies in a specific genre and year.
# Tickets Sold: The total number of tickets sold for movies in a specific genre and year.
# Inflation-Adjusted Gross: The gross revenue adjusted for inflation, taking into account changes in the value of money over time.
# Top Movie: The title of the highest-grossing movie in a specific genre and year.
# Top Movie Gross (That Year): The gross revenue generated by the highest-grossing movie in a specific genre and year.
# Top Movie Inflation-Adjusted Gross (That Year): The inflation-adjusted gross revenue of the highest-grossing movie in a specific genre and year.

library(tidyverse)
library(latex2exp)
movies <- read.csv("ThrowbackDataThursday Week 11 - Film Genre Stats.csv", header = TRUE, sep = ",")
movies

# Ao todo, quantas variáveis e quantas observações existem no banco de dados?

print(paste("O número de linhas ou observações = ", dim(movies)[1]))
print(paste("O número de colunas ou variáveis = ", dim(movies)[2]))

# Popular Genres
# primeiro vamos ver os generos que temos, depois fazer o rank

movies_pop <- select(movies, Genre,Movies.Released,Tickets.Sold) %>%
  group_by(Genre) %>%
  summarise(Movies_Released = sum(Movies.Released), 
            Tickets_Sold = sum(Tickets.Sold),
            .groups = 'drop') %>%
  as.data.frame()

#controle no rank
movies_pop_mr <- movies_pop[order(movies_pop$Movies_Released,decreasing = TRUE),]
movies_pop_ts <- movies_pop[order(movies_pop$Tickets_Sold,decreasing = TRUE),]

# Movies Released Popularity
png(file="Images/Popularity of Genres by Movies Releasead.png", width = 1200, height = 800)
ggplot(movies_pop, aes(x=Movies_Released,y=reorder(Genre,Movies_Released))) + geom_bar(stat = 'identity')  + 
  labs(title = "Popular Genres", x = "Movies Released", y = " Genders") + 
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.background = element_rect(fill='transparent'),
    plot.background = element_rect(fill='transparent', color=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill='transparent'),
    legend.box.background = element_rect(fill='transparent')
)
dev.off()

# Tickets Sold Popularity
png(file="Images/Popularity of Genres by Tickets Sold.png", width = 1200, height = 800)
ggplot(movies_pop, aes(x=Tickets_Sold/100000,y=reorder(Genre,Tickets_Sold))) + geom_bar(stat = 'identity')  + 
  labs(title = "Popular Genres", x = TeX("Tickets Sold divided by $10^{5}$"), y = "Genres")  +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.background = element_rect(fill='transparent'),
    plot.background = element_rect(fill='transparent', color=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill='transparent'),
    legend.box.background = element_rect(fill='transparent')
  )
dev.off()

# Measuring Financial Success:  Gross, Inflation Adjusted Gross, or Top Movie Gross (That Year) to compare the financial success of different genres

# primeiro vamos ver os valores recebidos por genero de filme

movies_fs <- select(movies, Genre,Gross,Top.Movie.Gross..That.Year.) %>%
  group_by(Genre) %>%
  summarise(Total_Gross_genre = sum(Gross), 
            Top_Movie_Gross = max(Top.Movie.Gross..That.Year.),
            .groups = 'drop') %>%
  as.data.frame()

movies_fs['Top_Movie'] <- subset.data.frame(movies, Top.Movie.Gross..That.Year. == movies_fs[,'Top_Movie_Gross'], select=c(Top.Movie)) 

png(file="Images/Financial Success by genres.png", width=1200, height = 800)
ggplot(movies_fs, aes(x=Total_Gross_genre/10000000,y=reorder(Genre,Total_Gross_genre))) + geom_bar(stat = 'identity')  + 
  labs(title = "Financial Success by Genres", x ="Total Gross ($ 10 Million)", y = "Genres")  +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.background = element_rect(fill='transparent'),
    plot.background = element_rect(fill='transparent', color=NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill='transparent'),
    legend.box.background = element_rect(fill='transparent')
  )
dev.off()

movies_fs.query("Genre == 'Adventure'")